name: Kombin AWS Deployment Workflow

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Workflow
        run: echo "Workflow running successfully"